language: java
dist: trusty

cache:
  directories:
  - $HOME/.m2

before_script:
- unset -v _JAVA_OPTIONS
- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

jobs:
  include:
  - stage: jdk.java.net - OpenJDK - GPL
    env: JDK=8
    script: source install-jdk.sh -F 8

  - stage: Graal
    env: JDK=graalvm-19.0.0
    script: source install-jdk.sh --url https://github.com/oracle/graal/releases/download/vm-19.0.0/graalvm-ce-linux-amd64-19.0.0.tar.gz

after_script:
- echo fired by git webhook
- echo JAVA_HOME = ${JAVA_HOME}
- echo PATH = ${PATH}
- ls ${JAVA_HOME}
- java -version
- mvn --version