language: java
dist: trusty

cache:
  directories:
  - $HOME/.m2

before_install:
- unset -v _JAVA_OPTIONS
- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

before_script:
- export GRAALVM_HOME=$JAVA_HOME
- echo $GRAALVM_HOME
- echo ls $GRAALVM_HOME

jobs:
  include:
  - stage: build_jvm
    name: Build Java pgk usin OpenJDK 8
    env: JDK=8
    install: true
    script: ./mvnw package -DskipTests -Ddocker.skip

  - stage: build_native
    name: Build native pkg usin the GraalVM
    env: JDK=graalvm-19.0.0
    install: source install-jdk.sh --url https://github.com/oracle/graal/releases/download/vm-19.0.0/graalvm-ce-linux-amd64-19.0.0.tar.gz
    script: ./mvnw package -Dnative -DskipTests -Ddocker.skip

after_script:
- echo fired by git webhook
- echo JAVA_HOME = ${JAVA_HOME}
- echo PATH = ${PATH}
- ls ${JAVA_HOME}
- java -version
- mvn --version